networks:
  app_net:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 192.168.24.0/24

volumes:
  strata_blog_local_postgres_data: {}
  strata_blog_local_postgres_data_backups: {}
  strata_blog_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: strata_blog_local_django
    container_name: strata_blog_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    networks:
      - app_net

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: strata_blog_production_postgres
    container_name: strata_blog_local_postgres
    volumes:
      - strata_blog_local_postgres_data:/var/lib/postgresql/data
      - strata_blog_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - app_net

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: strata_blog_local_mailpit
    ports:
      - "8025:8025"
    networks:
      - app_net

  redis:
    image: docker.io/redis:6
    container_name: strata_blog_local_redis

    volumes:
      - strata_blog_local_redis_data:/data

  celeryworker:
    <<: *django
    image: strata_blog_local_celeryworker
    container_name: strata_blog_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: strata_blog_local_celerybeat
    container_name: strata_blog_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: strata_blog_local_flower
    container_name: strata_blog_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: strata_blog_local_node
    container_name: strata_blog_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - app_net

  nginx-proxy:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./strata_blog/media:/usr/share/nginx/media
      - ./compose/local/certs:/etc/nginx/certs
    restart: always
    depends_on:
      - mailpit
      - node
    networks:
      - app_net
