# Generated by Django 5.0.8 on 2024-08-12 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_post_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='users_comme_post_id_f5db10_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author_name'], name='users_comme_author__ad3975_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='users_comme_created_95fba1_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title'], name='users_post_title_858a24_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='users_post_created_01415a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='users_post_author__52a0a2_idx'),
        ),
    ]
